name: Publish Scala Binding to Maven Central

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: '21'
      - name: Build and publish
        run: |
          cd Bibliotecas/bindings/scala
          sbt publish
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
