name: Publish Ruby Binding to RubyGems

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - name: Build and publish gem
        run: |
          cd Bibliotecas/bindings/ruby
          gem build biblioteca.gemspec
          gem push biblioteca-*.gem --key rubygems --host https://rubygems.org
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
