name: Publish R Binding to CRAN

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Publish to CRAN
        run: |
          cd Bibliotecas/bindings/r
          R CMD build .
          R CMD check --as-cran Biblioteca_*.tar.gz
          R CMD INSTALL Biblioteca_*.tar.gz
          # Publicação manual via CRAN web
