name: Publish Haskell Binding to Hackage

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.6.4'
      - name: Build and publish
        run: |
          cd Bibliotecas/bindings/haskell
          cabal build
          cabal sdist
          cabal upload --username ${{ secrets.HACKAGE_USER }} --password ${{ secrets.HACKAGE_PASS }} dist/*
