name: Publish Rust Binding to crates.io

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Publish to crates.io
        run: |
          cd Bibliotecas/bindings/rust
          cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
