name: Publish Go Binding to pkg.go.dev

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Publish to pkg.go.dev
        run: |
          cd Bibliotecas/bindings/go
          go mod tidy
          go publish
